services:
  react:
    container_name: react
    image: react-frontend
    build: .
    environment:
      - REACT_APP_EXPRESS_URL=http://localhost:3001
    volumes: 
      - ./src:/app/src
    ports: 
      - 3000:3000
    networks:
      - cloudsolver

networks:
  cloudsolver:
    external: true
