services:
  gateway_app:
    container_name: gateway
    image: gateway-server
    build:
      context: .
      dockerfile: Dockerfile.development
    environment:
      - GCLOUD_PROJECT=dm885-cloud-solver
      - FIRESTORE_EMULATOR_HOST=firestore:8080
      - GATEWAY_PROGRAM_STAGE=dev
      - GATEWAY_ALLOW_ORIGIN=*
      - GATEWAY_COOKIE_SECRET=dev-secret
    ports:
      - 3001:3000
    volumes:
      - ./src:/app/src
      - ./package.json:/app/package.json