services:
  express:
    container_name: express
    image: express-backend
    build:
      context: .
      dockerfile: Dockerfile.development
    environment:
      - FIRESTORE_EMULATOR_HOST=emulator:8080
      - FIREBASE_STORAGE_EMULATOR_HOST=emulator:9199
      - NODE_ENV=dev
      - EXPRESS_ALLOW_ORIGIN=http://localhost:3000
    ports:
      - 3001:3000
    volumes:
      - ./src:/app/src
      - ./package.json:/app/package.json
      - ./tsconfig.json:/app/tsconfig.json
    networks:
      - cloudsolver

networks:
  cloudsolver:
    name: cloudsolver